config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'try', to: 'home#try'
  get 'profile', to: 'users#profile'

  devise_for :users
  resources :users

  resources :organizations, except: [:index] do
    resources :survey_templates, shallow: true do
      get 'trends(/:team_id)', action: 'trends', as: 'trends', on: :member

      resources :survey_questions, shallow: true, only: [:create, :update, :destroy]

      resources :surveys, shallow: true do
        resources :survey_responses, shallow: true, only: [:index, :new, :create] do
          get 'team/:team_id', action: 'team', as: 'team', on: :collection
          get 'thankyou', on: :collection
        end
      end
    end

    resources :teams, shallow: true do
      member do
        delete 'remove_member/:user_id', action: 'remove_member', as: 'remove_member_from'
        delete 'remove_admin/:user_id', action: 'remove_admin', as: 'remove_admin_from'
        post 'add_user', as: 'add_user_to'
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def try
    admin = User.find_by_email('admin@example.com')
    @team = admin.teams.where(name: 'Team A').first
    @survey = @team.organization.surveys.last
  end
end

app/views/home/index.html.erb
<script>
  $(function() {
    $('.slider').slider();
  });
</script>

<h1>Measure your team's health</h1>

<div class="slider">
  <ul class="slides">
    <li>
      <img src="/home_slider/survey.png">
      <div class="caption center-align">
        <h3 class="white-text">Capture the mood</h3>
        <h5 class="white-text">Get feedback about what's working, and what isn't.</h5>
      </div>
    </li>
    <li>
      <img src="/home_slider/team_responses.png"> <!-- random image -->
      <div class="caption left-align">
        <h3 class="white-text">Understand the team</h3>
        <h5 class="white-text">See how teams and individuals perceive their work.</h5>
      </div>
    </li>
    <li>
      <img src="/home_slider/org_responses.png"> <!-- random image -->
      <div class="caption right-align">
        <h3 class="white-text">Understand the organization</h3>
        <h5 class="white-text">Spot common problems across multiple teams.</h5>
      </div>
    </li>
    <li>
      <img src="/home_slider/trends.png"> <!-- random image -->
      <div class="caption center-align">
        <h3 class="white-text">Monitor trends</h3>
        <h5 class="white-text">See trends within teams and across the organization.</h5>
      </div>
    </li>
  </ul>
</div>

<h4>What is this?</h4>

<p>
  This will be an app for automating Spotify style
  <a href="https://labs.spotify.com/2014/09/16/squad-health-check-model/">squad health checks</a>.
</p>
<p>
  Please note: this app is currently in <b>alpha</b>. Please only try it if you're interested in contributing (whether
  product ideas or pull requests). While in alpha, this app may prove unstable, and your data may be lost.
</p>

<h4>Contributing</h4>

<p>
  Work in progress. Suggestions and contributions
  <a href="https://github.com/jbrunton/agileplanning-io-metrics/issues">welcome</a>.
</p>

app/views/home/try.html.erb
<h4>Try it out</h4>

<p>
  Try <%= link_to 'signing in', new_user_session_path, target: '_blank' %> as <b>user_1@example.com</b> to try out the survey and view results, or <b>admin@example.com</b> to
  see how administration functionality works. The password for both is <b>Password1</b>.
</p>

<p>
  Once signed in, take a look at:
  <ul>
    <li><%= link_to 'Survey results for a single team', team_survey_survey_responses_path(@survey, @team) %></li>
    <li><%= link_to 'Survey results for a whole organization', survey_survey_responses_path(@survey) %></li>
    <li><%= link_to 'Organization and team trends', trends_survey_template_path(@survey.survey_template) %></li>
  </ul>
</p>

<p>
  Note that the survey and organization data for these users may be reset from time to time.
</p>