config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'try', to: 'home#try'
  get 'profile', to: 'users#profile'

  devise_for :users
  resources :users

  resources :organizations, except: [:index] do
    resources :survey_templates, shallow: true do
      get 'trends(/:team_id)', action: 'trends', as: 'trends', on: :member

      resources :survey_questions, shallow: true, only: [:create, :update, :destroy]

      resources :surveys, shallow: true do
        resources :survey_responses, shallow: true, only: [:index, :new, :create] do
          get 'team/:team_id', action: 'team', as: 'team', on: :collection
          get 'thankyou', on: :collection
        end
      end
    end

    resources :teams, shallow: true do
      member do
        delete 'remove_member/:user_id', action: 'remove_member', as: 'remove_member_from'
        delete 'remove_admin/:user_id', action: 'remove_admin', as: 'remove_admin_from'
        post 'add_user', as: 'add_user_to'
      end
    end
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :survey_template
  has_many :survey_responses
  has_many :survey_answers, through: :survey_responses
  validates :name, presence: true

  RELATIONS_FOR_REPORTS = [
    :user,
    survey_answers: [
      :mood,
      :survey_response
    ]
  ]

  def rating_for(question, team = nil)
    # TODO: unit tests
    answers = survey_answers.where(survey_question_id: question.id).select do |answer|
      team.nil? || answer.survey_response.user.member_of?(team)
    end

    ratings = answers.map do |answer|
      answer.try(:mood).try(:weight)
    end.compact

    ratings.reduce(:+) / ratings.length
  end


  def responses_for(team)
    # TODO: unit tests
    survey_responses.includes(RELATIONS_FOR_REPORTS).select do |response|
      response.user.member_of?(team)
    end
  end

  def teams
    # TODO: unit tests
    survey_responses.map{ |response| response.user.teams(:member) }.flatten.uniq
  end

  def notify_recipients
    survey_template.recipients.each do |user|
      SurveyMailer.notify_survey(user, self).deliver_now
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :set_survey_template, only: [:index, :create, :new]
  before_action :authenticate_user!
  after_action :verify_authorized

  # GET /surveys
  # GET /surveys.json
  def index
    authorize @survey_template, :show_surveys?
    @surveys = @survey_template.surveys
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = @survey_template.surveys.build
    @survey.name = Time.zone.now.strftime("#{@survey_template.name} - %-d %b %Y")
    authorize @survey
    @record = [@survey_template, @survey]
  end

  # GET /surveys/1/edit
  def edit
    @record = @survey
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = @survey_template.surveys.build(survey_params)
    authorize @survey

    respond_to do |format|
      if @survey.save
        @survey.notify_recipients
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to survey_template_surveys_path(@survey_template), notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id])
    authorize @survey
    @survey_template = @survey.survey_template
  end

  def set_survey_template
    @survey_template = SurveyTemplate.find(params[:survey_template_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_params
    params.require(:survey).permit(:name, :survey_template_id)
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Survey</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Survey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= survey.survey_template %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_template_survey_path(@survey_template) %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

app/views/surveys/show.html.erb
<% breadcrumb :survey, @survey %>

<%= header_for(@survey) %>

<p>
  <strong>Template:</strong>
  <%= link_to @survey.survey_template.name, @survey.survey_template %>
</p>

<p class="center-align">
  <%= link_to 'Take the survey', new_survey_survey_response_path(@survey), class: 'btn' %>
  <%= link_to 'View results', survey_survey_responses_path(@survey), class: 'btn btn-flat' %>
  <%= link_to 'View trends', trends_survey_template_path(@survey.survey_template), class: 'btn btn-flat' %>
</p>