config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'try', to: 'home#try'
  get 'profile', to: 'users#profile'

  devise_for :users
  resources :users

  resources :organizations, except: [:index] do
    resources :survey_templates, shallow: true do
      get 'trends(/:team_id)', action: 'trends', as: 'trends', on: :member

      resources :survey_questions, shallow: true, only: [:create, :update, :destroy]

      resources :surveys, shallow: true do
        resources :survey_responses, shallow: true, only: [:index, :new, :create] do
          get 'team/:team_id', action: 'team', as: 'team', on: :collection
          get 'thankyou', on: :collection
        end
      end
    end

    resources :teams, shallow: true do
      member do
        delete 'remove_member/:user_id', action: 'remove_member', as: 'remove_member_from'
        delete 'remove_admin/:user_id', action: 'remove_admin', as: 'remove_admin_from'
        post 'add_user', as: 'add_user_to'
      end
    end
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  resourcify
  validates :name, presence: true
  has_many :teams
  has_many :survey_templates
  has_many :surveys, through: :survey_templates
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  layout 'blank', only: [:show]

  before_action :set_organization, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:create, :new]

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    include_options = {
      survey_templates: {
        surveys: :survey_template
      }
    }
    @organization = Organization.includes(include_options).find(params[:id])
    authorize @organization
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        current_user.add_role :admin, @organization
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find(params[:id])
    authorize @organization
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= form_input(@organization, :name) %>
      </div>
    </div>
    <div class="actions">
      <%= submit_button %>
      <% unless @organization.new_record? %>
          <%= cancel_button @organization %>
      <% end %>
    </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

app/views/organizations/show.html.erb
<% breadcrumb :organization, @organization %>
<script>
  $(function () {
    $('#search').on('keyup', function (e) {
      var $search = $('#search');
      if (escapePressed(e)) {
        $search.val('');
      }

      var query = $search.val().toLowerCase();
      if (query.length == 0) {
        clearSearch();
        return;
      }

      $('.team').each(function (index, team) {
        var $tokens = $(team).find('.token');
        var matches = $tokens.filter(function (index, token) {
          return matchToken(query, token);
        });
        $(team).toggle(matches.length > 0);
      });
    });

    function escapePressed(e) {
      return e.keyCode == 27;
    }

    function clearSearch() {
      $('.token').removeClass('match');
      $('.team').show();
    }

    function queryMatches(query, text) {
      return text.toLowerCase().includes(query);
    }

    function matchToken(query, token) {
      var $token = $(token);
      if (queryMatches(query, $token.text())) {
        $token.addClass('match');
        return true;
      } else {
        $token.removeClass('match');
        return false;
      }
    }
  });
</script>

<div class="page-content">
  <%= breadcrumbs %>

  <%= header_for(@organization) %>

  <p>
    <strong>Name:</strong>
    <%= @organization.name %>
  </p>
</div>
<div class="page-content">

  <ul class="tabs">
    <li class="tab"><a href="#teams">Teams</a></li>
    <li class="tab"><a href="#surveys">Surveys</a></li>
    <li class="tab"><a href="#templates">Trends & Templates</a></li>
  </ul>

  <div id="teams">
    <div class="row">
      <form class="col s12">
        <div class="row">
          <div class="input-field col s12 search">
            <i class="material-icons prefix">search</i>
            <input id="search" type="text" required>
            <label for="search">Search</label>
          </div>
        </div>
      </form>
    </div>

    <table class="bordered">
      <tr>
        <th width="20%">Team</th>
        <th width="60%">Members</th>
        <th width="20%">Admins</th>
      </tr>
      <% @organization.teams.each do |team| %>
          <tr class="team">
            <td>
              <span class="token"><%= link_to team.name, team %></span>
            </td>
            <td>
              <% team.members.each do |user| %>
                  <div class="chip">
                    <span class="token"><%= link_to user.email, user %></span>
                  </div>
              <% end %>
            </td>
            <td>
              <% team.admins.each do |user| %>
                  <div class="chip">
                    <span class="token"><%= link_to user.email, user %></span>
                  </div>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>

  <div id="surveys">
    <table>
      <tr>
        <th>Name</th>
        <th>Template</th>
      </tr>
      <% @organization.surveys.each do |survey| %>
          <tr>
            <td><%= link_to survey.name, survey %></td>
            <td><%= link_to survey.survey_template.name, survey.survey_template %></td>
          </tr>
      <% end %>
    </table>
  </div>

  <div id="templates">
    <table>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
      </tr>
      <% @organization.survey_templates.each do |survey_template| %>
          <tr>
            <td><%= link_to survey_template.name, survey_template %></td>
            <td><%= survey_template.description %></td>
            <td><%= link_to 'Trends', trends_survey_template_path(survey_template) %></td>
          </tr>
      <% end %>
    </table>
  </div>

</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">add</i>
  </a>
  <ul>
    <li>
      <a href="<%= new_organization_survey_template_path(@organization) %>" class="btn-floating blue tooltipped" data-position="left" data-tooltip="new template">
        <i class="material-icons">add_box</i>
      </a>
    </li>
    <li>
      <a class="btn-floating green tooltipped" data-position="left" data-tooltip="send survey" onclick="$('#modal-new-survey').openModal();">
        <i class="material-icons">forum</i>
      </a>
    </li>
    <li>
      <a href="<%= new_organization_team_path(@organization) %>" class="btn-floating yellow darken-2 tooltipped" data-position="left" data-tooltip="add team">
        <i class="material-icons">group_add</i>
      </a>
    </li>
  </ul>
</div>

<!-- Modal Structure -->
<div id="modal-new-survey" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>New Survey</h4>
    <p>Please select which template to use.</p>
    <ul class="collection with-header">
      <% @organization.survey_templates.each do |survey_template| %>
          <%= link_to survey_template.name, new_survey_template_survey_path(survey_template), class: 'collection-item' %>
      <% end %>
    </ul>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
  </div>
</div>

app/views/organizations/trends.html.erb
<% breadcrumb :organization_trends, @survey_template %>

<h5>Trends for <b><%= @organization.name %> <%= @survey_template.name %></b></h5>

<table>
  <tr>
    <th>Question</th>
    <% @surveys.each do |survey| %>
        <th><%= survey.created_at.strftime('%-d %b %y') %></th>
    <% end %>

    <% @survey_template.survey_questions.each do |question| %>
        <tr>
          <td>
            <%= question.title %>
          </td>

          <% @surveys.each do |survey| %>
              <td>
                <%= mood_img(survey.rating_for(question)) %>
              </td>
          <% end %>
        </tr>
    <% end %>
  </tr>
</table>