config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'try', to: 'home#try'
  get 'profile', to: 'users#profile'

  devise_for :users
  resources :users

  resources :organizations, except: [:index] do
    resources :survey_templates, shallow: true do
      get 'trends(/:team_id)', action: 'trends', as: 'trends', on: :member

      resources :survey_questions, shallow: true, only: [:create, :update, :destroy]

      resources :surveys, shallow: true do
        resources :survey_responses, shallow: true, only: [:index, :new, :create] do
          get 'team/:team_id', action: 'team', as: 'team', on: :collection
          get 'thankyou', on: :collection
        end
      end
    end

    resources :teams, shallow: true do
      member do
        delete 'remove_member/:user_id', action: 'remove_member', as: 'remove_member_from'
        delete 'remove_admin/:user_id', action: 'remove_admin', as: 'remove_admin_from'
        post 'add_user', as: 'add_user_to'
      end
    end
  end

end

app/models/survey_template.rb
class SurveyTemplate < ActiveRecord::Base
  belongs_to :organization
  validates :name, presence: true
  has_many :survey_questions
  has_many :surveys

  def recipients
    organization.teams.map(&:members).flatten.uniq
  end
end

app/controllers/survey_templates_controller.rb
class SurveyTemplatesController < ApplicationController
  layout 'blank', only: [:show]
  before_action :set_survey_template, only: [:show, :edit, :update, :destroy, :trends]
  before_action :set_organization, only: [:new, :create, :index]
  before_action :authenticate_user!
  after_action :verify_authorized

  # GET /survey_templates
  # GET /survey_templates.json
  def index
    authorize @organization, :show_templates?
    @survey_templates = @organization.survey_templates
  end

  # GET /survey_templates/1
  # GET /survey_templates/1.json
  def show
  end

  # GET /survey_templates/1/trends
  # GET /survey_templates/1/trends.json
  def trends
    @team = Team.find(params[:team_id]) if params[:team_id]
    if @team.nil?
      include_options = {
        survey_responses: {
          survey_answers: [:mood]
        }
      }
    else
      include_options = {
        survey_responses: Survey::RELATIONS_FOR_REPORTS
      }
    end
    @surveys = @survey_template.surveys.includes(include_options).order(:created_at)
  end

  # GET /survey_templates/new
  def new
    @survey_template = @organization.survey_templates.build
    authorize @survey_template
    @record = [@organization, @survey_template]
  end

  # GET /survey_templates/1/edit
  def edit
    @record = @survey_template
  end

  # POST /survey_templates
  # POST /survey_templates.json
  def create
    @survey_template = @organization.survey_templates.build(survey_template_params)
    authorize @survey_template

    respond_to do |format|
      if @survey_template.save
        format.html { redirect_to @survey_template, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @survey_template }
      else
        @record = [@organization, @survey_template]
        format.html { render :new }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_templates/1
  # PATCH/PUT /survey_templates/1.json
  def update
    respond_to do |format|
      if @survey_template.update(survey_template_params)
        format.html { redirect_to @survey_template, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_template }
      else
        @record = @survey_template
        format.html { render :edit }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_templates/1
  # DELETE /survey_templates/1.json
  def destroy
    @survey_template.destroy
    respond_to do |format|
      format.html { redirect_to organization_survey_templates_url(@organization), notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_survey_template
    @survey_template = SurveyTemplate.find(params[:id])
    authorize @survey_template
    @organization = @survey_template.organization
  end

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_template_params
    params.require(:survey_template).permit(:name, :description, :organization_id)
  end
end

app/helpers/survey_templates_helper.rb
module SurveyTemplatesHelper
end

app/views/survey_templates/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @survey_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @survey_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survey_templates/edit.html.erb
<h1>Editing Survey Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_template %> |

app/views/survey_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Survey Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_templates.each do |survey_template| %>
      <tr>
        <td><%= survey_template.name %></td>
        <td><%= survey_template.description %></td>
        <td><%= survey_template.organization %></td>
        <td><%= link_to 'Show', survey_template %></td>
        <td><%= link_to 'Edit', edit_survey_template_path(survey_template) %></td>
        <td><%= link_to 'Destroy', survey_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey Template', new_organization_survey_template_path(@organization) %>

app/views/survey_templates/new.html.erb
<h1>New Survey Template</h1>

<%= render 'form' %>

app/views/survey_templates/show.html.erb
<% breadcrumb :survey_template, @survey_template %>

<script>
  $(function() {
    $('.edit-question').hide();

    $('body').on('click', '.edit-question .cancel', function () {
      $(this).closest('.edit-question').hide();
      return true;
    });

    $('#add-question').click(function() {
      $('#modal-add-question').openModal();
    });

    $('.edit-question-link').click(function(e) {
      $(e.target).closest('.show-question').hide();
      $(e.target).closest('.show-question').next().show();
    });

    $('.edit-question .cancel').click(function(e) {
      $(e.target).closest('.edit-question').hide();
      $(e.target).closest('.edit-question').prev().show();
    });

    $('form').submit(function(e) {
      var url = $(this).attr('action');
      var data = $(this).serialize();
      $.ajax({
        type: 'POST',
        url: url,
        data: data,
        success: function() {
          window.location = window.location;
        }
      });
      e.preventDefault();
    });
  });
</script>

<div class="page-content">
  <%= breadcrumbs %>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @survey_template.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @survey_template.description %>
  </p>

  <p>
    <strong>Organization:</strong>
    <%= @survey_template.organization %>
  </p>

  <%= link_to 'Edit', edit_survey_template_path(@survey_template) %> |
</div>

<div class="page-content">
  <table>
    <tr>
      <th>Question</th>
      <th>Summary</th>
    </tr>
    <% @survey_template.survey_questions.each do |question| %>
        <tr class="show-question">
          <td width="33%">
            <%= question.title %>
          </td>
          <td width="66%" style="position: relative;">
            <%= question.text %>
            <a style="position: absolute; top: 0; right: -60px;" class="btn-floating edit-question-link teal"><i class="material-icons">mode_edit</i></a>
          </td>
        </tr>
        <tr class="edit-question">
          <td colspan="3">
            <%= form_tag(survey_question_path(question, format: :json), method: :put) do %>
                <div class="row">
                  <div class="input-field col s4">
                    <input id="survey_question_title" name="survey_question[title]" type="text" class="validate" value="<%= question.title %>">
                    <label for="survey_question_title">Title</label>
                  </div>
                  <div class="input-field col s8">
                    <input id="survey_question_text" name="survey_question[text]" type="text" class="validate" value="<%= question.text%>">
                    <label for="survey_question_text">Text</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col s12">
                    <button class="submit btn">Submit</button>
                    <button type="button" class="cancel btn-flat">Cancel</button>
                  </div>
                </div>
            <% end %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

<div class="fixed-action-btn">
  <button id="add-question" class="fab">
    <i class="large material-icons">add</i>
  </button>
</div>

<!-- Modal Structure -->
<div id="modal-add-question" class="modal">
  <%= form_tag(survey_template_survey_questions_path(@survey_template, format: :json), method: :post) do %>
  <div class="modal-content">
    <h4>Add Question</h4>
    <div class="row">
      <div class="input-field col s12">
        <input id="new_question_title" name="survey_question[title]" type="text" class="validate">
        <label for="new_question_title">Title</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <input id="new_question_text" name="survey_question[text]" type="text" class="validate">
        <label for="new_question_text">Text</label>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</button>
    <button id="create-question" class="btn">Add</button>
  </div>
  <% end %>
</div>

app/views/survey_templates/trends.html.erb
<script>
  $(function () {
    $('#select-team').on('change', function (e) {
      var teamId = $(e.target).val();
      var newPath = '<%= trends_survey_template_path(@survey_template) %>';
      if (teamId != '') {
        newPath += '/' + teamId;
      }
      window.location = newPath;
    });
  });
</script>

<% if @team.nil? %>
    <% breadcrumb :organization_trends, @survey_template %>
    <h5>Trends for <b><%= @organization.name %> <%= @survey_template.name %></b></h5>
<% else %>
    <% breadcrumb :team_trends, @team, @survey_template %>
    <h5>Trends for <b><%= @team.name %> <%= @survey_template.name %></b></h5>
<% end %>

<div class="input-field col s12">
  <select id="select-team">
    <option <%= @team.nil? ? 'selected disabled' : '' %> value=""><% if @team.nil? %>Drill down to team<% else %>Organization Trends<% end %></option>
    <% @survey_template.organization.teams.each do |team| %>
        <option <%= @team.try(:id) == team.id ? 'selected' : '' %> value="<%= team.id %>"><%= team.name %></option>
    <% end %>
  </select>
</div>

<table>
  <tr>
    <th>Question</th>
    <% @surveys.each do |survey| %>
        <th><%= survey.created_at.strftime('%-d %b %y') %></th>
    <% end %>

    <% @survey_template.survey_questions.each do |question| %>
        <tr>
          <td>
            <%= question.title %>
          </td>

          <% @surveys.each do |survey| %>
              <td>
                <%= mood_img(survey.rating_for(question, @team)) %>
              </td>
          <% end %>
        </tr>
    <% end %>
  </tr>
</table>